# Generated by Django 6.1.1 on 2026-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=30, verbose_name='Resultado')),
                ('medio', models.CharField(choices=[('WEB', 'Web'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('PRESENCIAL', 'Presencial'), ('OTRO', 'Otro')], max_length=30, verbose_name='Medio')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Aprobación de servicio',
                'verbose_name_plural': 'Aprobaciones de servicio',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / contacto')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de componente')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('ADICIONAL', 'Adicional')], default='INICIAL', max_length=30, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del ítem')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Valor')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL / referencia (Cloudflare)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción'), ('DIAGNOSTICO', 'Diagnóstico'), ('REPARACION', 'Reparación'), ('PRUEBA', 'Prueba'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('visible_cliente', models.BooleanField(default=False, verbose_name='Visible al cliente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_REVISION', 'En revisión'), ('COTIZANDO', 'Cotizando'), ('ESPERANDO_APROBACION', 'Esperando aprobación'), ('EN_REPARACION', 'En reparación'), ('EN_PRUEBAS', 'En pruebas'), ('FINALIZADO', 'Finalizado'), ('LISTO_PARA_ENTREGA', 'Listo para entrega'), ('ENTREGADO', 'Entregado'), ('NO_APROBADO', 'No aprobado'), ('CANCELADO', 'Cancelado')], max_length=30, verbose_name='Estado alcanzado')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('visible_cliente', models.BooleanField(default=False, verbose_name='Visible al cliente')),
            ],
            options={
                'verbose_name': 'Historial de servicio',
                'verbose_name_plural': 'Historial de servicios',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código')),
                ('tipo_servicio', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('REPARACION', 'Reparación'), ('MANTENIMIENTO', 'Mantenimiento'), ('PRUEBA', 'Prueba'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de servicio')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_REVISION', 'En revisión'), ('COTIZANDO', 'Cotizando'), ('ESPERANDO_APROBACION', 'Esperando aprobación'), ('EN_REPARACION', 'En reparación'), ('EN_PRUEBAS', 'En pruebas'), ('FINALIZADO', 'Finalizado'), ('LISTO_PARA_ENTREGA', 'Listo para entrega'), ('ENTREGADO', 'Entregado'), ('NO_APROBADO', 'No aprobado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=30, verbose_name='Estado')),
                ('descripcion_solicitud', models.TextField(verbose_name='Descripción de la solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('token_seguimiento', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de seguimiento')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones internas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
