# Generated by Django 6.1.1 on 2026-09-28 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobacionservicio',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='aprobacionservicio',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='servicios.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='subida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografias', to=settings.AUTH_USER_MODEL, verbose_name='Subida por'),
        ),
        migrations.AddField(
            model_name='historialservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_servicios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historialservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='componente',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='servicios.servicio', verbose_name='Servicio'),
        ),
    ]
