# Generated by Django 6.1.1 on 2026-10-04 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_BLOQUEANTE', 'Rechazado (bloqueante)'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO_POR_CLIENTE', 'Finalizado por cliente'), ('FINALIZADO_POR_TECNICO', 'Finalizado por técnico')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fase',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DESMONTAJE_INICIADO', 'Desmontaje iniciado'), ('EN_EJECUCION', 'En ejecución')], default='RECIBIDO', max_length=30, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fecha_inicio_trabajo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de trabajo'),
        ),
        migrations.AddField(
            model_name='componente',
            name='motivo_finalizacion',
            field=models.CharField(blank=True, choices=[('FINALIZADO_POR_CLIENTE', 'Finalizado por cliente'), ('FINALIZADO_POR_TECNICO', 'Finalizado por técnico')], max_length=30, verbose_name='Motivo de finalización'),
        ),
        migrations.AddField(
            model_name='componente',
            name='trabajo_iniciado',
            field=models.BooleanField(default=False, verbose_name='Trabajo iniciado'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='canal',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('WHATSAPP', 'WhatsApp')], max_length=30, verbose_name='Canal de respuesta'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='servicios.componente', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='es_bloqueante',
            field=models.BooleanField(default=False, verbose_name='Es bloqueante'),
        ),
        migrations.CreateModel(
            name='HistorialComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_BLOQUEANTE', 'Rechazado (bloqueante)'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO_POR_CLIENTE', 'Finalizado por cliente'), ('FINALIZADO_POR_TECNICO', 'Finalizado por técnico')], max_length=30, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_BLOQUEANTE', 'Rechazado (bloqueante)'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO_POR_CLIENTE', 'Finalizado por cliente'), ('FINALIZADO_POR_TECNICO', 'Finalizado por técnico')], max_length=30, verbose_name='Estado nuevo')),
                ('fase_registrada', models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('DESMONTAJE_INICIADO', 'Desmontaje iniciado'), ('EN_EJECUCION', 'En ejecución')], max_length=30, verbose_name='Fase registrada')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.componente', verbose_name='Componente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_componentes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de componente',
                'verbose_name_plural': 'Historial de componentes',
                'ordering': ['fecha'],
            },
        ),
    ]
